services:
  psql:
    build:
      context: ./
      dockerfile: ./docker/psql/Dockerfile
    container_name: egazette-psql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwe
      - POSTGRES_DB=egazette
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./
      dockerfile: ./docker/api/Dockerfile
    container_name: egazette-api
    ports:
      - 8000:8000
    environment:
      - POSTGRES_HOST_ADDRESS=host.docker.internal
      - POSTGRES_HOST_PORT=5432
      - SERVER_PORT=8000
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwe
      - POSTGRES_DB=egazette
      - SSL_MODE=disable
    depends_on:
      psql:
        condition: service_healthy
    command: bash -c "go mod download && go build -o bin/app && cd bin/ && ./app"
